mail:
  # image: tvial/docker-mailserver
  build: .
  hostname: mail
  domainname: my-domain.com
  ports:
  - "25:25"
  - "143:143"
  - "587:587"
  - "993:993"
  environment:
    docker_mail_domain: "my-domain.com"
    # format is user@domain.tld|clear_password
    docker_mail_users:
      - "username1@my-domain.com|username1password"
      - "username2@my-domain.com|username2password"
    # format is user@domain.tld|list,of,aliases,comma,separated
    docker_mail_aliases:
      - "username1@my-domain.com|alias1,alias2,alias3"
      - "username2@my-domain.com|alias4"